package ro.zg.mdb.constants;

public enum MdbErrorType {
    REQUIRED, GET_FIELD_ERROR,SET_FIELD_ERROR, UNKNOWN_FIELD, OBJECT_MATERIALIZATION_ERROR, VALIDATION_ERROR, UNKNOWN_SEQUENCE, UNIQUENESS_VIOLATED, PERSISTENCE_ERROR, UPDATE_ERROR;
}
